services:
  golang-service:
    image: golang-service
    build:
      context: golang-service
      dockerfile: ./Dockerfile
    ports:
      - 3002:8080
    volumes:
      - ./golang-service:/usr/src/app
    command: ["yarn", "start"]

  node-service:
    image: node-service
    build:
      context: node-service
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3000
    volumes:
      - ./node-service/index.js:/usr/src/app/index.js
    command: ["yarn", "start"]

  react-web-app:
    image: react-web-app
    build:
      context: react-web-app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./react-web-app/index.js:/usr/src/app/index.js
    command: ["yarn", "start"]
