services:
  nodewebapp:
    image: nodewebapp
    build:
      context: node-web-app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["yarn", "start:debug"]
