services:
  node-web-app:
    image: node-web-app
    build:
      context: node-web-app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./node-web-app/index.js:/usr/src/app/index.js
    command: ["yarn", "start"]

  node-web-api:
    image: node-web-api
    build:
      context: node-web-api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3000
    volumes:
      - ./node-web-api/index.js:/usr/src/app/index.js
    command: ["yarn", "start"]
