services:
  node-web-app:
    image: node-web-app
    build:
      context: node-web-app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["yarn", "start:debug"]
    
  node-web-api:
    image: node-web-api
    build:
      context: node-web-api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3001:3000
      - 9230:9229
    command: ["yarn", "start:debug"]
